### ISSUE TITLE
Project is being sunset

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/opentelemetry-exporter-dotnet#14]
See [OSS lifecycle and practices](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md)

This project has outlived its useful lifespan, and will be archived in the future. Honeycomb supports [OTLP ingest directly](https://docs.honeycomb.io/getting-data-in/dotnet/opentelemetry-distro/), which renders this exporter obsolete.

If you are actively using this exporter, please comment on this issue with your use case.

**Comment by MikeGoldsmith** [comment]
Closing as per #20
