### ISSUE TITLE
Duration reported is always truncated to < 1000ms

### ISSUE THREAD

**Issue by joshclark** [honeycombio/opentelemetry-exporter-dotnet#18]
We observed that we never saw a trace duration longer than 1 second.  We know we have longer running traces so we knew something was up.

In `HoneycombExporter.GenerateEvent` [line 65](https://github.com/honeycombio/opentelemetry-dotnet/blob/main/src/Honeycomb.OpenTelemetry/HoneycombExporter.cs#L65)  you can see the problem:

``` csharp
ev.Data.Add("duration_ms", activity.Duration.Milliseconds);
```

Duration is a TimeSpan.  TimeSpan.Milliseconds returns the milliseconds portion of the timespan but will always be in the range of 0-999.  The code should be using `Timespan.TotalMilliseconds` to get the full duration expressed as milliseconds.

**Comment by vreynolds** [comment]
@joshclark please see #14

**Comment by joshclark** [comment]
Your sunset description makes it sound like this project just isn't needed anymore, but its more than that.  With this bug, the project just doesn't work (unless all your traces are less than a second).  If you are not going to fix a bug that pretty much makes this project worthless, you might as well just archive it and be done.

**Comment by vreynolds** [comment]
Thanks for letting us know about the bug. As you can see, this project did not receive much TLC, and will be archived soon. There were a non-zero number of artifact downloads (most likely CI pipelines), so we wanted to extend some grace to folks that may have picked it up (even if it doesn't work as expected).

If you're looking for an OpenTelemetry instrumentation solution, either the OG [opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet) or the [Honeycomb distro](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet) are viable options.

**Comment by MikeGoldsmith** [comment]
Closing as per #20
