### ISSUE TITLE
Not updated to OpenTelemetry 0.6.0-beta.1

### ISSUE THREAD

**Issue by adamchester** [honeycombio/opentelemetry-exporter-dotnet#3]
This library is a little out of date, as it references Otel `0.2.0-alpha.179`

I have updated the library to work with https://www.nuget.org/packages/OpenTelemetry.Api/0.6.0-beta.1

I can send a PR if there is interest.

**Comment by MikeGoldsmith** [comment]
Hi @adamchester - I intend to upgrade the SDK to the latest beta this week. Thanks.
